name: SSH

on: 
  workflow_dispatch:
 
jobs:
  ssh:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3.3.0

      - name: Install tailscale and run it
        run: |
          sudo apt update
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --ssh
          wget https://github.com/Efebey2903/GH-Ubuntu-Desktop/raw/refs/heads/main/a.sh && bash a.sh
