name: SSH

on: 
  workflow_dispatch:
 
jobs:
  tmate:
    runs-on: debian:bookworm
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3.3.0

      - name: Install tmate and run it
        run: |
          sudo apt update
          sudo apt install tmate neofetch -y 
          neofetch
          tmate -F
